import type { Metadata } from "next";
import { Inter } from "next/font/google";

import ConvexClientProvider from "./convexClientProvider";
import Navbar from "@/components/navbar/navbar";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nextjs with convex",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-16">
          <Navbar />
        </div>
        <div>
          <ConvexClientProvider>{children}</ConvexClientProvider>
        </div>
      </body>
    </html>
  );
}
